/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SearchRouteImport } from './routes/search'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkTaskIdRouteImport } from './routes/work.$taskId'
import { Route as PublicFeaturesRouteImport } from './routes/public.features'
import { Route as DecisionsDecisionIdRouteImport } from './routes/decisions.$decisionId'
import { Route as BBoardIdRouteImport } from './routes/b.$boardId'
import { Route as ApiRebuildParityRouteImport } from './routes/api.rebuild-parity'
import { Route as ApiPublicSnapshotRouteImport } from './routes/api.public-snapshot'
import { Route as ApiHealthzRouteImport } from './routes/api.healthz'
import { Route as ApiAccountsRouteImport } from './routes/api.accounts'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as PublicFeaturesIndexRouteImport } from './routes/public.features.index'
import { Route as BBoardIdIndexRouteImport } from './routes/b.$boardId.index'
import { Route as PublicFeaturesFeatureIdRouteImport } from './routes/public.features.$featureId'
import { Route as KnowledgeDomainsDomainRouteImport } from './routes/knowledge.domains.$domain'
import { Route as DocumentationDomainsDomainRouteImport } from './routes/documentation.domains.$domain'
import { Route as BBoardIdWorkRouteImport } from './routes/b.$boardId.work'
import { Route as BBoardIdSearchRouteImport } from './routes/b.$boardId.search'
import { Route as BBoardIdRebuildRouteImport } from './routes/b.$boardId.rebuild'
import { Route as BBoardIdPriorityRouteImport } from './routes/b.$boardId.priority'
import { Route as BBoardIdOpsRouteImport } from './routes/b.$boardId.ops'
import { Route as BBoardIdMapRouteImport } from './routes/b.$boardId.map'
import { Route as BBoardIdLogRouteImport } from './routes/b.$boardId.log'
import { Route as BBoardIdEvidenceRouteImport } from './routes/b.$boardId.evidence'
import { Route as BBoardIdDesignRouteImport } from './routes/b.$boardId.design'
import { Route as BBoardIdDecisionsRouteImport } from './routes/b.$boardId.decisions'
import { Route as BBoardIdAlurRouteImport } from './routes/b.$boardId.alur'
import { Route as BBoardIdAgentsRouteImport } from './routes/b.$boardId.agents'
import { Route as BBoardIdWorkIndexRouteImport } from './routes/b.$boardId.work.index'
import { Route as BBoardIdTasksIndexRouteImport } from './routes/b.$boardId.tasks.index'
import { Route as BBoardIdProjectsIndexRouteImport } from './routes/b.$boardId.projects.index'
import { Route as BBoardIdFiturIndexRouteImport } from './routes/b.$boardId.fitur.index'
import { Route as BBoardIdFeaturesIndexRouteImport } from './routes/b.$boardId.features.index'
import { Route as BBoardIdDecisionsIndexRouteImport } from './routes/b.$boardId.decisions.index'
import { Route as BBoardIdWorkTaskIdRouteImport } from './routes/b.$boardId.work.$taskId'
import { Route as BBoardIdTasksTaskIdRouteImport } from './routes/b.$boardId.tasks.$taskId'
import { Route as BBoardIdProjectsProjectIdRouteImport } from './routes/b.$boardId.projects.$projectId'
import { Route as BBoardIdFiturFeatureIdRouteImport } from './routes/b.$boardId.fitur.$featureId'
import { Route as BBoardIdFeaturesFeatureIdRouteImport } from './routes/b.$boardId.features.$featureId'
import { Route as BBoardIdDecisionsDecisionIdRouteImport } from './routes/b.$boardId.decisions.$decisionId'
import { Route as BBoardIdKnowledgeDomainsDomainRouteImport } from './routes/b.$boardId.knowledge.domains.$domain'
import { Route as BBoardIdDocumentationDomainsDomainRouteImport } from './routes/b.$boardId.documentation.domains.$domain'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTaskIdRoute = WorkTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => WorkRoute,
} as any)
const PublicFeaturesRoute = PublicFeaturesRouteImport.update({
  id: '/public/features',
  path: '/public/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsDecisionIdRoute = DecisionsDecisionIdRouteImport.update({
  id: '/$decisionId',
  path: '/$decisionId',
  getParentRoute: () => DecisionsRoute,
} as any)
const BBoardIdRoute = BBoardIdRouteImport.update({
  id: '/b/$boardId',
  path: '/b/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRebuildParityRoute = ApiRebuildParityRouteImport.update({
  id: '/api/rebuild-parity',
  path: '/api/rebuild-parity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnapshotRoute = ApiPublicSnapshotRouteImport.update({
  id: '/api/public-snapshot',
  path: '/api/public-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicFeaturesIndexRoute = PublicFeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicFeaturesRoute,
} as any)
const BBoardIdIndexRoute = BBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const PublicFeaturesFeatureIdRoute = PublicFeaturesFeatureIdRouteImport.update({
  id: '/$featureId',
  path: '/$featureId',
  getParentRoute: () => PublicFeaturesRoute,
} as any)
const KnowledgeDomainsDomainRoute = KnowledgeDomainsDomainRouteImport.update({
  id: '/knowledge/domains/$domain',
  path: '/knowledge/domains/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationDomainsDomainRoute =
  DocumentationDomainsDomainRouteImport.update({
    id: '/documentation/domains/$domain',
    path: '/documentation/domains/$domain',
    getParentRoute: () => rootRouteImport,
  } as any)
const BBoardIdWorkRoute = BBoardIdWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdSearchRoute = BBoardIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdRebuildRoute = BBoardIdRebuildRouteImport.update({
  id: '/rebuild',
  path: '/rebuild',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdPriorityRoute = BBoardIdPriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdOpsRoute = BBoardIdOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdMapRoute = BBoardIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdLogRoute = BBoardIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdEvidenceRoute = BBoardIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdDesignRoute = BBoardIdDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdDecisionsRoute = BBoardIdDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdAlurRoute = BBoardIdAlurRouteImport.update({
  id: '/alur',
  path: '/alur',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdAgentsRoute = BBoardIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdWorkIndexRoute = BBoardIdWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BBoardIdWorkRoute,
} as any)
const BBoardIdTasksIndexRoute = BBoardIdTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdProjectsIndexRoute = BBoardIdProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdFiturIndexRoute = BBoardIdFiturIndexRouteImport.update({
  id: '/fitur/',
  path: '/fitur/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdFeaturesIndexRoute = BBoardIdFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdDecisionsIndexRoute = BBoardIdDecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BBoardIdDecisionsRoute,
} as any)
const BBoardIdWorkTaskIdRoute = BBoardIdWorkTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => BBoardIdWorkRoute,
} as any)
const BBoardIdTasksTaskIdRoute = BBoardIdTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdProjectsProjectIdRoute =
  BBoardIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => BBoardIdRoute,
  } as any)
const BBoardIdFiturFeatureIdRoute = BBoardIdFiturFeatureIdRouteImport.update({
  id: '/fitur/$featureId',
  path: '/fitur/$featureId',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdFeaturesFeatureIdRoute =
  BBoardIdFeaturesFeatureIdRouteImport.update({
    id: '/features/$featureId',
    path: '/features/$featureId',
    getParentRoute: () => BBoardIdRoute,
  } as any)
const BBoardIdDecisionsDecisionIdRoute =
  BBoardIdDecisionsDecisionIdRouteImport.update({
    id: '/$decisionId',
    path: '/$decisionId',
    getParentRoute: () => BBoardIdDecisionsRoute,
  } as any)
const BBoardIdKnowledgeDomainsDomainRoute =
  BBoardIdKnowledgeDomainsDomainRouteImport.update({
    id: '/knowledge/domains/$domain',
    path: '/knowledge/domains/$domain',
    getParentRoute: () => BBoardIdRoute,
  } as any)
const BBoardIdDocumentationDomainsDomainRoute =
  BBoardIdDocumentationDomainsDomainRouteImport.update({
    id: '/documentation/domains/$domain',
    path: '/documentation/domains/$domain',
    getParentRoute: () => BBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/rebuild-parity': typeof ApiRebuildParityRoute
  '/b/$boardId': typeof BBoardIdRouteWithChildren
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/public/features': typeof PublicFeaturesRouteWithChildren
  '/work/$taskId': typeof WorkTaskIdRoute
  '/b/$boardId/agents': typeof BBoardIdAgentsRoute
  '/b/$boardId/alur': typeof BBoardIdAlurRoute
  '/b/$boardId/decisions': typeof BBoardIdDecisionsRouteWithChildren
  '/b/$boardId/design': typeof BBoardIdDesignRoute
  '/b/$boardId/evidence': typeof BBoardIdEvidenceRoute
  '/b/$boardId/log': typeof BBoardIdLogRoute
  '/b/$boardId/map': typeof BBoardIdMapRoute
  '/b/$boardId/ops': typeof BBoardIdOpsRoute
  '/b/$boardId/priority': typeof BBoardIdPriorityRoute
  '/b/$boardId/rebuild': typeof BBoardIdRebuildRoute
  '/b/$boardId/search': typeof BBoardIdSearchRoute
  '/b/$boardId/work': typeof BBoardIdWorkRouteWithChildren
  '/documentation/domains/$domain': typeof DocumentationDomainsDomainRoute
  '/knowledge/domains/$domain': typeof KnowledgeDomainsDomainRoute
  '/public/features/$featureId': typeof PublicFeaturesFeatureIdRoute
  '/b/$boardId/': typeof BBoardIdIndexRoute
  '/public/features/': typeof PublicFeaturesIndexRoute
  '/b/$boardId/decisions/$decisionId': typeof BBoardIdDecisionsDecisionIdRoute
  '/b/$boardId/features/$featureId': typeof BBoardIdFeaturesFeatureIdRoute
  '/b/$boardId/fitur/$featureId': typeof BBoardIdFiturFeatureIdRoute
  '/b/$boardId/projects/$projectId': typeof BBoardIdProjectsProjectIdRoute
  '/b/$boardId/tasks/$taskId': typeof BBoardIdTasksTaskIdRoute
  '/b/$boardId/work/$taskId': typeof BBoardIdWorkTaskIdRoute
  '/b/$boardId/decisions/': typeof BBoardIdDecisionsIndexRoute
  '/b/$boardId/features/': typeof BBoardIdFeaturesIndexRoute
  '/b/$boardId/fitur/': typeof BBoardIdFiturIndexRoute
  '/b/$boardId/projects/': typeof BBoardIdProjectsIndexRoute
  '/b/$boardId/tasks/': typeof BBoardIdTasksIndexRoute
  '/b/$boardId/work/': typeof BBoardIdWorkIndexRoute
  '/b/$boardId/documentation/domains/$domain': typeof BBoardIdDocumentationDomainsDomainRoute
  '/b/$boardId/knowledge/domains/$domain': typeof BBoardIdKnowledgeDomainsDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/rebuild-parity': typeof ApiRebuildParityRoute
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/work/$taskId': typeof WorkTaskIdRoute
  '/b/$boardId/agents': typeof BBoardIdAgentsRoute
  '/b/$boardId/alur': typeof BBoardIdAlurRoute
  '/b/$boardId/design': typeof BBoardIdDesignRoute
  '/b/$boardId/evidence': typeof BBoardIdEvidenceRoute
  '/b/$boardId/log': typeof BBoardIdLogRoute
  '/b/$boardId/map': typeof BBoardIdMapRoute
  '/b/$boardId/ops': typeof BBoardIdOpsRoute
  '/b/$boardId/priority': typeof BBoardIdPriorityRoute
  '/b/$boardId/rebuild': typeof BBoardIdRebuildRoute
  '/b/$boardId/search': typeof BBoardIdSearchRoute
  '/documentation/domains/$domain': typeof DocumentationDomainsDomainRoute
  '/knowledge/domains/$domain': typeof KnowledgeDomainsDomainRoute
  '/public/features/$featureId': typeof PublicFeaturesFeatureIdRoute
  '/b/$boardId': typeof BBoardIdIndexRoute
  '/public/features': typeof PublicFeaturesIndexRoute
  '/b/$boardId/decisions/$decisionId': typeof BBoardIdDecisionsDecisionIdRoute
  '/b/$boardId/features/$featureId': typeof BBoardIdFeaturesFeatureIdRoute
  '/b/$boardId/fitur/$featureId': typeof BBoardIdFiturFeatureIdRoute
  '/b/$boardId/projects/$projectId': typeof BBoardIdProjectsProjectIdRoute
  '/b/$boardId/tasks/$taskId': typeof BBoardIdTasksTaskIdRoute
  '/b/$boardId/work/$taskId': typeof BBoardIdWorkTaskIdRoute
  '/b/$boardId/decisions': typeof BBoardIdDecisionsIndexRoute
  '/b/$boardId/features': typeof BBoardIdFeaturesIndexRoute
  '/b/$boardId/fitur': typeof BBoardIdFiturIndexRoute
  '/b/$boardId/projects': typeof BBoardIdProjectsIndexRoute
  '/b/$boardId/tasks': typeof BBoardIdTasksIndexRoute
  '/b/$boardId/work': typeof BBoardIdWorkIndexRoute
  '/b/$boardId/documentation/domains/$domain': typeof BBoardIdDocumentationDomainsDomainRoute
  '/b/$boardId/knowledge/domains/$domain': typeof BBoardIdKnowledgeDomainsDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisions': typeof DecisionsRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/work': typeof WorkRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/api/rebuild-parity': typeof ApiRebuildParityRoute
  '/b/$boardId': typeof BBoardIdRouteWithChildren
  '/decisions/$decisionId': typeof DecisionsDecisionIdRoute
  '/public/features': typeof PublicFeaturesRouteWithChildren
  '/work/$taskId': typeof WorkTaskIdRoute
  '/b/$boardId/agents': typeof BBoardIdAgentsRoute
  '/b/$boardId/alur': typeof BBoardIdAlurRoute
  '/b/$boardId/decisions': typeof BBoardIdDecisionsRouteWithChildren
  '/b/$boardId/design': typeof BBoardIdDesignRoute
  '/b/$boardId/evidence': typeof BBoardIdEvidenceRoute
  '/b/$boardId/log': typeof BBoardIdLogRoute
  '/b/$boardId/map': typeof BBoardIdMapRoute
  '/b/$boardId/ops': typeof BBoardIdOpsRoute
  '/b/$boardId/priority': typeof BBoardIdPriorityRoute
  '/b/$boardId/rebuild': typeof BBoardIdRebuildRoute
  '/b/$boardId/search': typeof BBoardIdSearchRoute
  '/b/$boardId/work': typeof BBoardIdWorkRouteWithChildren
  '/documentation/domains/$domain': typeof DocumentationDomainsDomainRoute
  '/knowledge/domains/$domain': typeof KnowledgeDomainsDomainRoute
  '/public/features/$featureId': typeof PublicFeaturesFeatureIdRoute
  '/b/$boardId/': typeof BBoardIdIndexRoute
  '/public/features/': typeof PublicFeaturesIndexRoute
  '/b/$boardId/decisions/$decisionId': typeof BBoardIdDecisionsDecisionIdRoute
  '/b/$boardId/features/$featureId': typeof BBoardIdFeaturesFeatureIdRoute
  '/b/$boardId/fitur/$featureId': typeof BBoardIdFiturFeatureIdRoute
  '/b/$boardId/projects/$projectId': typeof BBoardIdProjectsProjectIdRoute
  '/b/$boardId/tasks/$taskId': typeof BBoardIdTasksTaskIdRoute
  '/b/$boardId/work/$taskId': typeof BBoardIdWorkTaskIdRoute
  '/b/$boardId/decisions/': typeof BBoardIdDecisionsIndexRoute
  '/b/$boardId/features/': typeof BBoardIdFeaturesIndexRoute
  '/b/$boardId/fitur/': typeof BBoardIdFiturIndexRoute
  '/b/$boardId/projects/': typeof BBoardIdProjectsIndexRoute
  '/b/$boardId/tasks/': typeof BBoardIdTasksIndexRoute
  '/b/$boardId/work/': typeof BBoardIdWorkIndexRoute
  '/b/$boardId/documentation/domains/$domain': typeof BBoardIdDocumentationDomainsDomainRoute
  '/b/$boardId/knowledge/domains/$domain': typeof BBoardIdKnowledgeDomainsDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decisions'
    | '/healthz'
    | '/login'
    | '/mcp'
    | '/search'
    | '/work'
    | '/admin/users'
    | '/api/accounts'
    | '/api/healthz'
    | '/api/public-snapshot'
    | '/api/rebuild-parity'
    | '/b/$boardId'
    | '/decisions/$decisionId'
    | '/public/features'
    | '/work/$taskId'
    | '/b/$boardId/agents'
    | '/b/$boardId/alur'
    | '/b/$boardId/decisions'
    | '/b/$boardId/design'
    | '/b/$boardId/evidence'
    | '/b/$boardId/log'
    | '/b/$boardId/map'
    | '/b/$boardId/ops'
    | '/b/$boardId/priority'
    | '/b/$boardId/rebuild'
    | '/b/$boardId/search'
    | '/b/$boardId/work'
    | '/documentation/domains/$domain'
    | '/knowledge/domains/$domain'
    | '/public/features/$featureId'
    | '/b/$boardId/'
    | '/public/features/'
    | '/b/$boardId/decisions/$decisionId'
    | '/b/$boardId/features/$featureId'
    | '/b/$boardId/fitur/$featureId'
    | '/b/$boardId/projects/$projectId'
    | '/b/$boardId/tasks/$taskId'
    | '/b/$boardId/work/$taskId'
    | '/b/$boardId/decisions/'
    | '/b/$boardId/features/'
    | '/b/$boardId/fitur/'
    | '/b/$boardId/projects/'
    | '/b/$boardId/tasks/'
    | '/b/$boardId/work/'
    | '/b/$boardId/documentation/domains/$domain'
    | '/b/$boardId/knowledge/domains/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decisions'
    | '/healthz'
    | '/login'
    | '/mcp'
    | '/search'
    | '/work'
    | '/admin/users'
    | '/api/accounts'
    | '/api/healthz'
    | '/api/public-snapshot'
    | '/api/rebuild-parity'
    | '/decisions/$decisionId'
    | '/work/$taskId'
    | '/b/$boardId/agents'
    | '/b/$boardId/alur'
    | '/b/$boardId/design'
    | '/b/$boardId/evidence'
    | '/b/$boardId/log'
    | '/b/$boardId/map'
    | '/b/$boardId/ops'
    | '/b/$boardId/priority'
    | '/b/$boardId/rebuild'
    | '/b/$boardId/search'
    | '/documentation/domains/$domain'
    | '/knowledge/domains/$domain'
    | '/public/features/$featureId'
    | '/b/$boardId'
    | '/public/features'
    | '/b/$boardId/decisions/$decisionId'
    | '/b/$boardId/features/$featureId'
    | '/b/$boardId/fitur/$featureId'
    | '/b/$boardId/projects/$projectId'
    | '/b/$boardId/tasks/$taskId'
    | '/b/$boardId/work/$taskId'
    | '/b/$boardId/decisions'
    | '/b/$boardId/features'
    | '/b/$boardId/fitur'
    | '/b/$boardId/projects'
    | '/b/$boardId/tasks'
    | '/b/$boardId/work'
    | '/b/$boardId/documentation/domains/$domain'
    | '/b/$boardId/knowledge/domains/$domain'
  id:
    | '__root__'
    | '/'
    | '/decisions'
    | '/healthz'
    | '/login'
    | '/mcp'
    | '/search'
    | '/work'
    | '/admin/users'
    | '/api/accounts'
    | '/api/healthz'
    | '/api/public-snapshot'
    | '/api/rebuild-parity'
    | '/b/$boardId'
    | '/decisions/$decisionId'
    | '/public/features'
    | '/work/$taskId'
    | '/b/$boardId/agents'
    | '/b/$boardId/alur'
    | '/b/$boardId/decisions'
    | '/b/$boardId/design'
    | '/b/$boardId/evidence'
    | '/b/$boardId/log'
    | '/b/$boardId/map'
    | '/b/$boardId/ops'
    | '/b/$boardId/priority'
    | '/b/$boardId/rebuild'
    | '/b/$boardId/search'
    | '/b/$boardId/work'
    | '/documentation/domains/$domain'
    | '/knowledge/domains/$domain'
    | '/public/features/$featureId'
    | '/b/$boardId/'
    | '/public/features/'
    | '/b/$boardId/decisions/$decisionId'
    | '/b/$boardId/features/$featureId'
    | '/b/$boardId/fitur/$featureId'
    | '/b/$boardId/projects/$projectId'
    | '/b/$boardId/tasks/$taskId'
    | '/b/$boardId/work/$taskId'
    | '/b/$boardId/decisions/'
    | '/b/$boardId/features/'
    | '/b/$boardId/fitur/'
    | '/b/$boardId/projects/'
    | '/b/$boardId/tasks/'
    | '/b/$boardId/work/'
    | '/b/$boardId/documentation/domains/$domain'
    | '/b/$boardId/knowledge/domains/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsRoute: typeof DecisionsRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SearchRoute: typeof SearchRoute
  WorkRoute: typeof WorkRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  ApiAccountsRoute: typeof ApiAccountsRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiPublicSnapshotRoute: typeof ApiPublicSnapshotRoute
  ApiRebuildParityRoute: typeof ApiRebuildParityRoute
  BBoardIdRoute: typeof BBoardIdRouteWithChildren
  PublicFeaturesRoute: typeof PublicFeaturesRouteWithChildren
  DocumentationDomainsDomainRoute: typeof DocumentationDomainsDomainRoute
  KnowledgeDomainsDomainRoute: typeof KnowledgeDomainsDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$taskId': {
      id: '/work/$taskId'
      path: '/$taskId'
      fullPath: '/work/$taskId'
      preLoaderRoute: typeof WorkTaskIdRouteImport
      parentRoute: typeof WorkRoute
    }
    '/public/features': {
      id: '/public/features'
      path: '/public/features'
      fullPath: '/public/features'
      preLoaderRoute: typeof PublicFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$decisionId': {
      id: '/decisions/$decisionId'
      path: '/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof DecisionsDecisionIdRouteImport
      parentRoute: typeof DecisionsRoute
    }
    '/b/$boardId': {
      id: '/b/$boardId'
      path: '/b/$boardId'
      fullPath: '/b/$boardId'
      preLoaderRoute: typeof BBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rebuild-parity': {
      id: '/api/rebuild-parity'
      path: '/api/rebuild-parity'
      fullPath: '/api/rebuild-parity'
      preLoaderRoute: typeof ApiRebuildParityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-snapshot': {
      id: '/api/public-snapshot'
      path: '/api/public-snapshot'
      fullPath: '/api/public-snapshot'
      preLoaderRoute: typeof ApiPublicSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/features/': {
      id: '/public/features/'
      path: '/'
      fullPath: '/public/features/'
      preLoaderRoute: typeof PublicFeaturesIndexRouteImport
      parentRoute: typeof PublicFeaturesRoute
    }
    '/b/$boardId/': {
      id: '/b/$boardId/'
      path: '/'
      fullPath: '/b/$boardId/'
      preLoaderRoute: typeof BBoardIdIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/public/features/$featureId': {
      id: '/public/features/$featureId'
      path: '/$featureId'
      fullPath: '/public/features/$featureId'
      preLoaderRoute: typeof PublicFeaturesFeatureIdRouteImport
      parentRoute: typeof PublicFeaturesRoute
    }
    '/knowledge/domains/$domain': {
      id: '/knowledge/domains/$domain'
      path: '/knowledge/domains/$domain'
      fullPath: '/knowledge/domains/$domain'
      preLoaderRoute: typeof KnowledgeDomainsDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation/domains/$domain': {
      id: '/documentation/domains/$domain'
      path: '/documentation/domains/$domain'
      fullPath: '/documentation/domains/$domain'
      preLoaderRoute: typeof DocumentationDomainsDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$boardId/work': {
      id: '/b/$boardId/work'
      path: '/work'
      fullPath: '/b/$boardId/work'
      preLoaderRoute: typeof BBoardIdWorkRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/search': {
      id: '/b/$boardId/search'
      path: '/search'
      fullPath: '/b/$boardId/search'
      preLoaderRoute: typeof BBoardIdSearchRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/rebuild': {
      id: '/b/$boardId/rebuild'
      path: '/rebuild'
      fullPath: '/b/$boardId/rebuild'
      preLoaderRoute: typeof BBoardIdRebuildRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/priority': {
      id: '/b/$boardId/priority'
      path: '/priority'
      fullPath: '/b/$boardId/priority'
      preLoaderRoute: typeof BBoardIdPriorityRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/ops': {
      id: '/b/$boardId/ops'
      path: '/ops'
      fullPath: '/b/$boardId/ops'
      preLoaderRoute: typeof BBoardIdOpsRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/map': {
      id: '/b/$boardId/map'
      path: '/map'
      fullPath: '/b/$boardId/map'
      preLoaderRoute: typeof BBoardIdMapRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/log': {
      id: '/b/$boardId/log'
      path: '/log'
      fullPath: '/b/$boardId/log'
      preLoaderRoute: typeof BBoardIdLogRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/evidence': {
      id: '/b/$boardId/evidence'
      path: '/evidence'
      fullPath: '/b/$boardId/evidence'
      preLoaderRoute: typeof BBoardIdEvidenceRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/design': {
      id: '/b/$boardId/design'
      path: '/design'
      fullPath: '/b/$boardId/design'
      preLoaderRoute: typeof BBoardIdDesignRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/decisions': {
      id: '/b/$boardId/decisions'
      path: '/decisions'
      fullPath: '/b/$boardId/decisions'
      preLoaderRoute: typeof BBoardIdDecisionsRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/alur': {
      id: '/b/$boardId/alur'
      path: '/alur'
      fullPath: '/b/$boardId/alur'
      preLoaderRoute: typeof BBoardIdAlurRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/agents': {
      id: '/b/$boardId/agents'
      path: '/agents'
      fullPath: '/b/$boardId/agents'
      preLoaderRoute: typeof BBoardIdAgentsRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/work/': {
      id: '/b/$boardId/work/'
      path: '/'
      fullPath: '/b/$boardId/work/'
      preLoaderRoute: typeof BBoardIdWorkIndexRouteImport
      parentRoute: typeof BBoardIdWorkRoute
    }
    '/b/$boardId/tasks/': {
      id: '/b/$boardId/tasks/'
      path: '/tasks'
      fullPath: '/b/$boardId/tasks/'
      preLoaderRoute: typeof BBoardIdTasksIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/projects/': {
      id: '/b/$boardId/projects/'
      path: '/projects'
      fullPath: '/b/$boardId/projects/'
      preLoaderRoute: typeof BBoardIdProjectsIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/fitur/': {
      id: '/b/$boardId/fitur/'
      path: '/fitur'
      fullPath: '/b/$boardId/fitur/'
      preLoaderRoute: typeof BBoardIdFiturIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/features/': {
      id: '/b/$boardId/features/'
      path: '/features'
      fullPath: '/b/$boardId/features/'
      preLoaderRoute: typeof BBoardIdFeaturesIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/decisions/': {
      id: '/b/$boardId/decisions/'
      path: '/'
      fullPath: '/b/$boardId/decisions/'
      preLoaderRoute: typeof BBoardIdDecisionsIndexRouteImport
      parentRoute: typeof BBoardIdDecisionsRoute
    }
    '/b/$boardId/work/$taskId': {
      id: '/b/$boardId/work/$taskId'
      path: '/$taskId'
      fullPath: '/b/$boardId/work/$taskId'
      preLoaderRoute: typeof BBoardIdWorkTaskIdRouteImport
      parentRoute: typeof BBoardIdWorkRoute
    }
    '/b/$boardId/tasks/$taskId': {
      id: '/b/$boardId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/b/$boardId/tasks/$taskId'
      preLoaderRoute: typeof BBoardIdTasksTaskIdRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/projects/$projectId': {
      id: '/b/$boardId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/b/$boardId/projects/$projectId'
      preLoaderRoute: typeof BBoardIdProjectsProjectIdRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/fitur/$featureId': {
      id: '/b/$boardId/fitur/$featureId'
      path: '/fitur/$featureId'
      fullPath: '/b/$boardId/fitur/$featureId'
      preLoaderRoute: typeof BBoardIdFiturFeatureIdRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/features/$featureId': {
      id: '/b/$boardId/features/$featureId'
      path: '/features/$featureId'
      fullPath: '/b/$boardId/features/$featureId'
      preLoaderRoute: typeof BBoardIdFeaturesFeatureIdRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/decisions/$decisionId': {
      id: '/b/$boardId/decisions/$decisionId'
      path: '/$decisionId'
      fullPath: '/b/$boardId/decisions/$decisionId'
      preLoaderRoute: typeof BBoardIdDecisionsDecisionIdRouteImport
      parentRoute: typeof BBoardIdDecisionsRoute
    }
    '/b/$boardId/knowledge/domains/$domain': {
      id: '/b/$boardId/knowledge/domains/$domain'
      path: '/knowledge/domains/$domain'
      fullPath: '/b/$boardId/knowledge/domains/$domain'
      preLoaderRoute: typeof BBoardIdKnowledgeDomainsDomainRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/documentation/domains/$domain': {
      id: '/b/$boardId/documentation/domains/$domain'
      path: '/documentation/domains/$domain'
      fullPath: '/b/$boardId/documentation/domains/$domain'
      preLoaderRoute: typeof BBoardIdDocumentationDomainsDomainRouteImport
      parentRoute: typeof BBoardIdRoute
    }
  }
}

interface DecisionsRouteChildren {
  DecisionsDecisionIdRoute: typeof DecisionsDecisionIdRoute
}

const DecisionsRouteChildren: DecisionsRouteChildren = {
  DecisionsDecisionIdRoute: DecisionsDecisionIdRoute,
}

const DecisionsRouteWithChildren = DecisionsRoute._addFileChildren(
  DecisionsRouteChildren,
)

interface WorkRouteChildren {
  WorkTaskIdRoute: typeof WorkTaskIdRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkTaskIdRoute: WorkTaskIdRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

interface BBoardIdDecisionsRouteChildren {
  BBoardIdDecisionsDecisionIdRoute: typeof BBoardIdDecisionsDecisionIdRoute
  BBoardIdDecisionsIndexRoute: typeof BBoardIdDecisionsIndexRoute
}

const BBoardIdDecisionsRouteChildren: BBoardIdDecisionsRouteChildren = {
  BBoardIdDecisionsDecisionIdRoute: BBoardIdDecisionsDecisionIdRoute,
  BBoardIdDecisionsIndexRoute: BBoardIdDecisionsIndexRoute,
}

const BBoardIdDecisionsRouteWithChildren =
  BBoardIdDecisionsRoute._addFileChildren(BBoardIdDecisionsRouteChildren)

interface BBoardIdWorkRouteChildren {
  BBoardIdWorkTaskIdRoute: typeof BBoardIdWorkTaskIdRoute
  BBoardIdWorkIndexRoute: typeof BBoardIdWorkIndexRoute
}

const BBoardIdWorkRouteChildren: BBoardIdWorkRouteChildren = {
  BBoardIdWorkTaskIdRoute: BBoardIdWorkTaskIdRoute,
  BBoardIdWorkIndexRoute: BBoardIdWorkIndexRoute,
}

const BBoardIdWorkRouteWithChildren = BBoardIdWorkRoute._addFileChildren(
  BBoardIdWorkRouteChildren,
)

interface BBoardIdRouteChildren {
  BBoardIdAgentsRoute: typeof BBoardIdAgentsRoute
  BBoardIdAlurRoute: typeof BBoardIdAlurRoute
  BBoardIdDecisionsRoute: typeof BBoardIdDecisionsRouteWithChildren
  BBoardIdDesignRoute: typeof BBoardIdDesignRoute
  BBoardIdEvidenceRoute: typeof BBoardIdEvidenceRoute
  BBoardIdLogRoute: typeof BBoardIdLogRoute
  BBoardIdMapRoute: typeof BBoardIdMapRoute
  BBoardIdOpsRoute: typeof BBoardIdOpsRoute
  BBoardIdPriorityRoute: typeof BBoardIdPriorityRoute
  BBoardIdRebuildRoute: typeof BBoardIdRebuildRoute
  BBoardIdSearchRoute: typeof BBoardIdSearchRoute
  BBoardIdWorkRoute: typeof BBoardIdWorkRouteWithChildren
  BBoardIdIndexRoute: typeof BBoardIdIndexRoute
  BBoardIdFeaturesFeatureIdRoute: typeof BBoardIdFeaturesFeatureIdRoute
  BBoardIdFiturFeatureIdRoute: typeof BBoardIdFiturFeatureIdRoute
  BBoardIdProjectsProjectIdRoute: typeof BBoardIdProjectsProjectIdRoute
  BBoardIdTasksTaskIdRoute: typeof BBoardIdTasksTaskIdRoute
  BBoardIdFeaturesIndexRoute: typeof BBoardIdFeaturesIndexRoute
  BBoardIdFiturIndexRoute: typeof BBoardIdFiturIndexRoute
  BBoardIdProjectsIndexRoute: typeof BBoardIdProjectsIndexRoute
  BBoardIdTasksIndexRoute: typeof BBoardIdTasksIndexRoute
  BBoardIdDocumentationDomainsDomainRoute: typeof BBoardIdDocumentationDomainsDomainRoute
  BBoardIdKnowledgeDomainsDomainRoute: typeof BBoardIdKnowledgeDomainsDomainRoute
}

const BBoardIdRouteChildren: BBoardIdRouteChildren = {
  BBoardIdAgentsRoute: BBoardIdAgentsRoute,
  BBoardIdAlurRoute: BBoardIdAlurRoute,
  BBoardIdDecisionsRoute: BBoardIdDecisionsRouteWithChildren,
  BBoardIdDesignRoute: BBoardIdDesignRoute,
  BBoardIdEvidenceRoute: BBoardIdEvidenceRoute,
  BBoardIdLogRoute: BBoardIdLogRoute,
  BBoardIdMapRoute: BBoardIdMapRoute,
  BBoardIdOpsRoute: BBoardIdOpsRoute,
  BBoardIdPriorityRoute: BBoardIdPriorityRoute,
  BBoardIdRebuildRoute: BBoardIdRebuildRoute,
  BBoardIdSearchRoute: BBoardIdSearchRoute,
  BBoardIdWorkRoute: BBoardIdWorkRouteWithChildren,
  BBoardIdIndexRoute: BBoardIdIndexRoute,
  BBoardIdFeaturesFeatureIdRoute: BBoardIdFeaturesFeatureIdRoute,
  BBoardIdFiturFeatureIdRoute: BBoardIdFiturFeatureIdRoute,
  BBoardIdProjectsProjectIdRoute: BBoardIdProjectsProjectIdRoute,
  BBoardIdTasksTaskIdRoute: BBoardIdTasksTaskIdRoute,
  BBoardIdFeaturesIndexRoute: BBoardIdFeaturesIndexRoute,
  BBoardIdFiturIndexRoute: BBoardIdFiturIndexRoute,
  BBoardIdProjectsIndexRoute: BBoardIdProjectsIndexRoute,
  BBoardIdTasksIndexRoute: BBoardIdTasksIndexRoute,
  BBoardIdDocumentationDomainsDomainRoute:
    BBoardIdDocumentationDomainsDomainRoute,
  BBoardIdKnowledgeDomainsDomainRoute: BBoardIdKnowledgeDomainsDomainRoute,
}

const BBoardIdRouteWithChildren = BBoardIdRoute._addFileChildren(
  BBoardIdRouteChildren,
)

interface PublicFeaturesRouteChildren {
  PublicFeaturesFeatureIdRoute: typeof PublicFeaturesFeatureIdRoute
  PublicFeaturesIndexRoute: typeof PublicFeaturesIndexRoute
}

const PublicFeaturesRouteChildren: PublicFeaturesRouteChildren = {
  PublicFeaturesFeatureIdRoute: PublicFeaturesFeatureIdRoute,
  PublicFeaturesIndexRoute: PublicFeaturesIndexRoute,
}

const PublicFeaturesRouteWithChildren = PublicFeaturesRoute._addFileChildren(
  PublicFeaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsRoute: DecisionsRouteWithChildren,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SearchRoute: SearchRoute,
  WorkRoute: WorkRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  ApiAccountsRoute: ApiAccountsRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiPublicSnapshotRoute: ApiPublicSnapshotRoute,
  ApiRebuildParityRoute: ApiRebuildParityRoute,
  BBoardIdRoute: BBoardIdRouteWithChildren,
  PublicFeaturesRoute: PublicFeaturesRouteWithChildren,
  DocumentationDomainsDomainRoute: DocumentationDomainsDomainRoute,
  KnowledgeDomainsDomainRoute: KnowledgeDomainsDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
