/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BBoardIdRouteImport } from './routes/b.$boardId'
import { Route as ApiPublicSnapshotRouteImport } from './routes/api.public-snapshot'
import { Route as ApiHealthzRouteImport } from './routes/api.healthz'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BBoardIdIndexRouteImport } from './routes/b.$boardId.index'
import { Route as BBoardIdWorkRouteImport } from './routes/b.$boardId.work'
import { Route as BBoardIdPriorityRouteImport } from './routes/b.$boardId.priority'
import { Route as BBoardIdOpsRouteImport } from './routes/b.$boardId.ops'
import { Route as BBoardIdMapRouteImport } from './routes/b.$boardId.map'
import { Route as BBoardIdLogRouteImport } from './routes/b.$boardId.log'
import { Route as BBoardIdEvidenceRouteImport } from './routes/b.$boardId.evidence'
import { Route as BBoardIdDesignRouteImport } from './routes/b.$boardId.design'
import { Route as BBoardIdDecisionsRouteImport } from './routes/b.$boardId.decisions'
import { Route as BBoardIdAgentsRouteImport } from './routes/b.$boardId.agents'
import { Route as BBoardIdTasksIndexRouteImport } from './routes/b.$boardId.tasks.index'
import { Route as BBoardIdProjectsIndexRouteImport } from './routes/b.$boardId.projects.index'
import { Route as BBoardIdFeaturesIndexRouteImport } from './routes/b.$boardId.features.index'
import { Route as BBoardIdTasksTaskIdRouteImport } from './routes/b.$boardId.tasks.$taskId'
import { Route as BBoardIdProjectsProjectIdRouteImport } from './routes/b.$boardId.projects.$projectId'
import { Route as BBoardIdFeaturesFeatureIdRouteImport } from './routes/b.$boardId.features.$featureId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BBoardIdRoute = BBoardIdRouteImport.update({
  id: '/b/$boardId',
  path: '/b/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnapshotRoute = ApiPublicSnapshotRouteImport.update({
  id: '/api/public-snapshot',
  path: '/api/public-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BBoardIdIndexRoute = BBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdWorkRoute = BBoardIdWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdPriorityRoute = BBoardIdPriorityRouteImport.update({
  id: '/priority',
  path: '/priority',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdOpsRoute = BBoardIdOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdMapRoute = BBoardIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdLogRoute = BBoardIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdEvidenceRoute = BBoardIdEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdDesignRoute = BBoardIdDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdDecisionsRoute = BBoardIdDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdAgentsRoute = BBoardIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdTasksIndexRoute = BBoardIdTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdProjectsIndexRoute = BBoardIdProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdFeaturesIndexRoute = BBoardIdFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdTasksTaskIdRoute = BBoardIdTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdProjectsProjectIdRoute =
  BBoardIdProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => BBoardIdRoute,
  } as any)
const BBoardIdFeaturesFeatureIdRoute =
  BBoardIdFeaturesFeatureIdRouteImport.update({
    id: '/features/$featureId',
    path: '/features/$featureId',
    getParentRoute: () => BBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/b/$boardId': typeof BBoardIdRouteWithChildren
  '/b/$boardId/agents': typeof BBoardIdAgentsRoute
  '/b/$boardId/decisions': typeof BBoardIdDecisionsRoute
  '/b/$boardId/design': typeof BBoardIdDesignRoute
  '/b/$boardId/evidence': typeof BBoardIdEvidenceRoute
  '/b/$boardId/log': typeof BBoardIdLogRoute
  '/b/$boardId/map': typeof BBoardIdMapRoute
  '/b/$boardId/ops': typeof BBoardIdOpsRoute
  '/b/$boardId/priority': typeof BBoardIdPriorityRoute
  '/b/$boardId/work': typeof BBoardIdWorkRoute
  '/b/$boardId/': typeof BBoardIdIndexRoute
  '/b/$boardId/features/$featureId': typeof BBoardIdFeaturesFeatureIdRoute
  '/b/$boardId/projects/$projectId': typeof BBoardIdProjectsProjectIdRoute
  '/b/$boardId/tasks/$taskId': typeof BBoardIdTasksTaskIdRoute
  '/b/$boardId/features/': typeof BBoardIdFeaturesIndexRoute
  '/b/$boardId/projects/': typeof BBoardIdProjectsIndexRoute
  '/b/$boardId/tasks/': typeof BBoardIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/b/$boardId/agents': typeof BBoardIdAgentsRoute
  '/b/$boardId/decisions': typeof BBoardIdDecisionsRoute
  '/b/$boardId/design': typeof BBoardIdDesignRoute
  '/b/$boardId/evidence': typeof BBoardIdEvidenceRoute
  '/b/$boardId/log': typeof BBoardIdLogRoute
  '/b/$boardId/map': typeof BBoardIdMapRoute
  '/b/$boardId/ops': typeof BBoardIdOpsRoute
  '/b/$boardId/priority': typeof BBoardIdPriorityRoute
  '/b/$boardId/work': typeof BBoardIdWorkRoute
  '/b/$boardId': typeof BBoardIdIndexRoute
  '/b/$boardId/features/$featureId': typeof BBoardIdFeaturesFeatureIdRoute
  '/b/$boardId/projects/$projectId': typeof BBoardIdProjectsProjectIdRoute
  '/b/$boardId/tasks/$taskId': typeof BBoardIdTasksTaskIdRoute
  '/b/$boardId/features': typeof BBoardIdFeaturesIndexRoute
  '/b/$boardId/projects': typeof BBoardIdProjectsIndexRoute
  '/b/$boardId/tasks': typeof BBoardIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/public-snapshot': typeof ApiPublicSnapshotRoute
  '/b/$boardId': typeof BBoardIdRouteWithChildren
  '/b/$boardId/agents': typeof BBoardIdAgentsRoute
  '/b/$boardId/decisions': typeof BBoardIdDecisionsRoute
  '/b/$boardId/design': typeof BBoardIdDesignRoute
  '/b/$boardId/evidence': typeof BBoardIdEvidenceRoute
  '/b/$boardId/log': typeof BBoardIdLogRoute
  '/b/$boardId/map': typeof BBoardIdMapRoute
  '/b/$boardId/ops': typeof BBoardIdOpsRoute
  '/b/$boardId/priority': typeof BBoardIdPriorityRoute
  '/b/$boardId/work': typeof BBoardIdWorkRoute
  '/b/$boardId/': typeof BBoardIdIndexRoute
  '/b/$boardId/features/$featureId': typeof BBoardIdFeaturesFeatureIdRoute
  '/b/$boardId/projects/$projectId': typeof BBoardIdProjectsProjectIdRoute
  '/b/$boardId/tasks/$taskId': typeof BBoardIdTasksTaskIdRoute
  '/b/$boardId/features/': typeof BBoardIdFeaturesIndexRoute
  '/b/$boardId/projects/': typeof BBoardIdProjectsIndexRoute
  '/b/$boardId/tasks/': typeof BBoardIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/admin/users'
    | '/api/healthz'
    | '/api/public-snapshot'
    | '/b/$boardId'
    | '/b/$boardId/agents'
    | '/b/$boardId/decisions'
    | '/b/$boardId/design'
    | '/b/$boardId/evidence'
    | '/b/$boardId/log'
    | '/b/$boardId/map'
    | '/b/$boardId/ops'
    | '/b/$boardId/priority'
    | '/b/$boardId/work'
    | '/b/$boardId/'
    | '/b/$boardId/features/$featureId'
    | '/b/$boardId/projects/$projectId'
    | '/b/$boardId/tasks/$taskId'
    | '/b/$boardId/features/'
    | '/b/$boardId/projects/'
    | '/b/$boardId/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/admin/users'
    | '/api/healthz'
    | '/api/public-snapshot'
    | '/b/$boardId/agents'
    | '/b/$boardId/decisions'
    | '/b/$boardId/design'
    | '/b/$boardId/evidence'
    | '/b/$boardId/log'
    | '/b/$boardId/map'
    | '/b/$boardId/ops'
    | '/b/$boardId/priority'
    | '/b/$boardId/work'
    | '/b/$boardId'
    | '/b/$boardId/features/$featureId'
    | '/b/$boardId/projects/$projectId'
    | '/b/$boardId/tasks/$taskId'
    | '/b/$boardId/features'
    | '/b/$boardId/projects'
    | '/b/$boardId/tasks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mcp'
    | '/admin/users'
    | '/api/healthz'
    | '/api/public-snapshot'
    | '/b/$boardId'
    | '/b/$boardId/agents'
    | '/b/$boardId/decisions'
    | '/b/$boardId/design'
    | '/b/$boardId/evidence'
    | '/b/$boardId/log'
    | '/b/$boardId/map'
    | '/b/$boardId/ops'
    | '/b/$boardId/priority'
    | '/b/$boardId/work'
    | '/b/$boardId/'
    | '/b/$boardId/features/$featureId'
    | '/b/$boardId/projects/$projectId'
    | '/b/$boardId/tasks/$taskId'
    | '/b/$boardId/features/'
    | '/b/$boardId/projects/'
    | '/b/$boardId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiPublicSnapshotRoute: typeof ApiPublicSnapshotRoute
  BBoardIdRoute: typeof BBoardIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$boardId': {
      id: '/b/$boardId'
      path: '/b/$boardId'
      fullPath: '/b/$boardId'
      preLoaderRoute: typeof BBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-snapshot': {
      id: '/api/public-snapshot'
      path: '/api/public-snapshot'
      fullPath: '/api/public-snapshot'
      preLoaderRoute: typeof ApiPublicSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$boardId/': {
      id: '/b/$boardId/'
      path: '/'
      fullPath: '/b/$boardId/'
      preLoaderRoute: typeof BBoardIdIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/work': {
      id: '/b/$boardId/work'
      path: '/work'
      fullPath: '/b/$boardId/work'
      preLoaderRoute: typeof BBoardIdWorkRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/priority': {
      id: '/b/$boardId/priority'
      path: '/priority'
      fullPath: '/b/$boardId/priority'
      preLoaderRoute: typeof BBoardIdPriorityRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/ops': {
      id: '/b/$boardId/ops'
      path: '/ops'
      fullPath: '/b/$boardId/ops'
      preLoaderRoute: typeof BBoardIdOpsRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/map': {
      id: '/b/$boardId/map'
      path: '/map'
      fullPath: '/b/$boardId/map'
      preLoaderRoute: typeof BBoardIdMapRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/log': {
      id: '/b/$boardId/log'
      path: '/log'
      fullPath: '/b/$boardId/log'
      preLoaderRoute: typeof BBoardIdLogRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/evidence': {
      id: '/b/$boardId/evidence'
      path: '/evidence'
      fullPath: '/b/$boardId/evidence'
      preLoaderRoute: typeof BBoardIdEvidenceRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/design': {
      id: '/b/$boardId/design'
      path: '/design'
      fullPath: '/b/$boardId/design'
      preLoaderRoute: typeof BBoardIdDesignRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/decisions': {
      id: '/b/$boardId/decisions'
      path: '/decisions'
      fullPath: '/b/$boardId/decisions'
      preLoaderRoute: typeof BBoardIdDecisionsRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/agents': {
      id: '/b/$boardId/agents'
      path: '/agents'
      fullPath: '/b/$boardId/agents'
      preLoaderRoute: typeof BBoardIdAgentsRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/tasks/': {
      id: '/b/$boardId/tasks/'
      path: '/tasks'
      fullPath: '/b/$boardId/tasks/'
      preLoaderRoute: typeof BBoardIdTasksIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/projects/': {
      id: '/b/$boardId/projects/'
      path: '/projects'
      fullPath: '/b/$boardId/projects/'
      preLoaderRoute: typeof BBoardIdProjectsIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/features/': {
      id: '/b/$boardId/features/'
      path: '/features'
      fullPath: '/b/$boardId/features/'
      preLoaderRoute: typeof BBoardIdFeaturesIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/tasks/$taskId': {
      id: '/b/$boardId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/b/$boardId/tasks/$taskId'
      preLoaderRoute: typeof BBoardIdTasksTaskIdRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/projects/$projectId': {
      id: '/b/$boardId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/b/$boardId/projects/$projectId'
      preLoaderRoute: typeof BBoardIdProjectsProjectIdRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/features/$featureId': {
      id: '/b/$boardId/features/$featureId'
      path: '/features/$featureId'
      fullPath: '/b/$boardId/features/$featureId'
      preLoaderRoute: typeof BBoardIdFeaturesFeatureIdRouteImport
      parentRoute: typeof BBoardIdRoute
    }
  }
}

interface BBoardIdRouteChildren {
  BBoardIdAgentsRoute: typeof BBoardIdAgentsRoute
  BBoardIdDecisionsRoute: typeof BBoardIdDecisionsRoute
  BBoardIdDesignRoute: typeof BBoardIdDesignRoute
  BBoardIdEvidenceRoute: typeof BBoardIdEvidenceRoute
  BBoardIdLogRoute: typeof BBoardIdLogRoute
  BBoardIdMapRoute: typeof BBoardIdMapRoute
  BBoardIdOpsRoute: typeof BBoardIdOpsRoute
  BBoardIdPriorityRoute: typeof BBoardIdPriorityRoute
  BBoardIdWorkRoute: typeof BBoardIdWorkRoute
  BBoardIdIndexRoute: typeof BBoardIdIndexRoute
  BBoardIdFeaturesFeatureIdRoute: typeof BBoardIdFeaturesFeatureIdRoute
  BBoardIdProjectsProjectIdRoute: typeof BBoardIdProjectsProjectIdRoute
  BBoardIdTasksTaskIdRoute: typeof BBoardIdTasksTaskIdRoute
  BBoardIdFeaturesIndexRoute: typeof BBoardIdFeaturesIndexRoute
  BBoardIdProjectsIndexRoute: typeof BBoardIdProjectsIndexRoute
  BBoardIdTasksIndexRoute: typeof BBoardIdTasksIndexRoute
}

const BBoardIdRouteChildren: BBoardIdRouteChildren = {
  BBoardIdAgentsRoute: BBoardIdAgentsRoute,
  BBoardIdDecisionsRoute: BBoardIdDecisionsRoute,
  BBoardIdDesignRoute: BBoardIdDesignRoute,
  BBoardIdEvidenceRoute: BBoardIdEvidenceRoute,
  BBoardIdLogRoute: BBoardIdLogRoute,
  BBoardIdMapRoute: BBoardIdMapRoute,
  BBoardIdOpsRoute: BBoardIdOpsRoute,
  BBoardIdPriorityRoute: BBoardIdPriorityRoute,
  BBoardIdWorkRoute: BBoardIdWorkRoute,
  BBoardIdIndexRoute: BBoardIdIndexRoute,
  BBoardIdFeaturesFeatureIdRoute: BBoardIdFeaturesFeatureIdRoute,
  BBoardIdProjectsProjectIdRoute: BBoardIdProjectsProjectIdRoute,
  BBoardIdTasksTaskIdRoute: BBoardIdTasksTaskIdRoute,
  BBoardIdFeaturesIndexRoute: BBoardIdFeaturesIndexRoute,
  BBoardIdProjectsIndexRoute: BBoardIdProjectsIndexRoute,
  BBoardIdTasksIndexRoute: BBoardIdTasksIndexRoute,
}

const BBoardIdRouteWithChildren = BBoardIdRoute._addFileChildren(
  BBoardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiPublicSnapshotRoute: ApiPublicSnapshotRoute,
  BBoardIdRoute: BBoardIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
